### ISSUE TITLE
Create ZLUX server.json containing defaults for container start

### ISSUE THREAD

**Issue by markjhollands** [zowe/zowe-container-sample#13]
Currently, the values for the TLS certificates are specified in the `docker-compose.yml` file as environment variables, as follows:
```yaml
services:
    zlux-app-server:
        environment:
            ZWED_node_https_keys: "/tls/tls.key,"
            ZWED_node_https_certificates: "/tls/tls.crt,"
            ZWED_node_https_certificateAuthorities: "/tls/ca.crt,"
```

As these values are automatically configured by other parts of the configuration they are unlikely to change, and could even be accidentally changed by a user.

These values should be configured in a default `server.json` file, and only values like agent hostname (`ZWED_agent_host`) should be overridden as environment variables.
